name: Executar Bot Binance

on:
  schedule:
    - cron: "*/30 * * * *"  # Executa a cada 30 minutos
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Instalar Dependências
        run: pip install -r requirements.txt  # Certifique-se de ter um arquivo requirements.txt

      - name: Executar Script
        run: python bot_binance.py  # Substitua pelo nome do seu script
